const fs = require('fs').promises
fs.mkdir('folder')
.then(()=>{console.log('folder is created')
    fs.mkdir('folder/bc')
    .then(()=>{console.log('folder is  created')
        fs.writeFile('folder/bc/bb.txt','bando')
        .then(()=>{console.log('file is written')
            fs.readFile('folder/bc/bb.txt','utf-8')
            .then((data)=>{console.log(data)})
            .catch((err)=>{console.log(err)})
        })
        .catch((err)=>{console.log(err)})
    })
    .catch((err)=>{console.log(err)})
})
.catch((err)=>{console.log(err)})